service: nohtaray-sample-app

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    SHOPIFY_API_KEY: ${env:SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET: ${env:SHOPIFY_API_SECRET}
    SCOPES: ${env:SCOPES}
    SHOP: ${env:SHOP}
    NODE_ENV: production

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - http:
          method: get
          path: /_next/{proxy+}
    package:
      include:
        - ../.next/**

custom:
  customDomain:
    domainName: shopify-${self:provider.stage}1.nohtaray.com
    stage: ${self:provider.stage}
    endpointType: regional
    certificateArn: arn:aws:acm:us-east-1:930038210242:certificate/80057b1a-c098-457d-ac7a-8410c0d26dbc
    certificateName: '*.nohtaray.com'
