service: nohtaray-sample-app

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    SHOPIFY_API_KEY: ${env:SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET: ${env:SHOPIFY_API_SECRET}
    SCOPES: ${env:SCOPES}
    IN_LAMBDA: true
    NODE_ENV: production
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
      - http:
          method: get
          path: /_next/{proxy+}
    package:
      exclude:
        - .git/**
  getShopProducts:
    handler: server/functions/getShopProducts.handler
    events:
      - http:
          method: get
          path: /api/{shop}/products
          request:
            parameters:
              paths:
                shop: true
  # TODO: 認証
  putShopProduct:
    handler: server/functions/putShopProduct.handler
    events:
      - http:
          method: post
          path: /api/{shop}/products/{product_id}/put
          request:
            parameters:
              paths:
                shop: true
                product_id: true
#  deleteShopProduct:
#    handler: server/functions/deleteShopProduct.handler
#    events:
#      - http:
#          method: post
#          path: /api/{shop}/products/{product_id}/delete
#          request:
#            parameters:
#              paths:
#                shop: true
#                product_id: true

custom:
  customDomain:
    domainName: ${self:provider.stage}-${self:service}.${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    endpointType: regional
