service: nohtaray-sample-app

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    SHOPIFY_API_KEY: ${env:SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET: ${env:SHOPIFY_API_SECRET}
    SCOPES: ${env:SCOPES}
    IN_LAMBDA: true
    NODE_ENV: production
  iamRoleStatements:
    - Effect: Allow
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
      Action:
        - "dynamodb:*"

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - http:
          method: get
          path: /_next/{proxy+}
    package:
      exclude:
        - .git/**
  getShopProducts:
    handler: server/functions/getShopProducts.handler

custom:
  customDomain:
    domainName: ${self:provider.stage}-${self:service}.${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    endpointType: regional
